server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankasarus
    username: ritik
    password: 12345
  application:
    name: ADMIN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: warn
  org:
    springframework:
      web: debug
    hibernate: error
