server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankasarus
    username: ritik
    password: 12345
  application:
    name: CUSTOMER
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: warn
  org:
    springframework:
      web: debug
    hibernate: error

# Actuator
management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ACCOUNTS_API:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnable: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
